/**
 * Test entry so `node --test lib-test/test/` (a directory argument resolves
 * to `lib-test/test/index.js`) picks up every compiled spec.
 */
import './keep-alive.js'
import './translate.spec.js'
import './chat-completions.spec.js'
import './models.spec.js'
import './codex-client-version.spec.js'
import './catalog-store.spec.js'
import './device-flow.spec.js'
import './copilot.spec.js'
import './antigravity.spec.js'
import './tools.spec.js'
import './image-pool.spec.js'
import './rpc.spec.js'
import './usage.spec.js'
import './subscription-usage-badge.spec.js'
import './rate-limit.spec.js'
import './detect-cli.spec.js'
import './login.spec.js'
import './store.spec.js'
import './accounts.spec.js'
import './pool.spec.js'
import './pool-health.spec.js'
import './pool-usage.spec.js'
import './grok.spec.js'
import './request-body.spec.js'
import './cache-affinity.spec.js'
import './proxy-host.spec.js'
import './model-defaults.spec.js'
import './model-defaults-rpc.spec.js'
import './model-defaults-view.spec.js'
import './provider-settings.spec.js'
import './provider-settings-rpc.spec.js'
import './client-command.spec.js'
import './tool-registration.spec.js'
